# Generated by Django 2.1.7 on 2019-04-12 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fourthapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profileinfo',
            name='userlink',
            field=models.EmailField(blank=True, max_length=254),
        ),
    ]
