# Generated by Django 2.1.7 on 2019-04-12 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fourthapp', '0002_auto_20190412_1030'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profileinfo',
            name='user_image',
            field=models.ImageField(blank=True, upload_to='profile_pics'),
        ),
    ]
